trigger:
  branches:
    include:
      - main
variables:
  buildConfiguration: Release
  vmImageName: windows-latest
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UseDotNet@2
            displayName: Force .NET 5
            inputs:
              packageType: sdk
              version: 5.x
          - task: DotNetCoreCLI@2
            displayName: Restore project
            inputs:
              command: restore
              projects: '**/albumtrackr.API.csproj'
              feedsToUse: select
          - task: DotNetCoreCLI@2
            displayName: Build Server
            inputs:
              command: build
              projects: '**/albumtrackr.API.csproj'
          - task: Gradle@2
            displayName: Building Android App
            inputs:
              workingDirectory: 'albumtrackr.App'
              gradleWrapperFile: 'albumtrackr.App/gradlew'
              tasks: 'build'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
  - stage: Release
    displayName: Release stage
    jobs:
      - job: Release
        displayName: Release to Azure
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UseDotNet@2
            displayName: Force .NET 5
            inputs:
              packageType: sdk
              version: 5.x
          - task: DotNetCoreCLI@2
            displayName: Restore API
            inputs:
              command: restore
              projects: '**/albumtrackr.API.csproj'
              feedsToUse: select
          - task: DotNetCoreCLI@2
            displayName: Publish API
            inputs:
              command: publish
              publishWebProjects: false
              projects: '**/albumtrackr.API.csproj'
          - task: AzureRmWebAppDeployment@4
            displayName: Deploy to Azure
            inputs:
              ConnectionType: AzureRM
              azureSubscription: albumtrackrAzure
              appType: webApp
              WebAppName: albumtrackrAPI
              packageForLinux: $(System.DefaultWorkingDirectory)/**/*.zip