// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using albumtrackr.API.Data;

namespace albumtrackr.API.Migrations
{
    [DbContext(typeof(AlbumtrackrContext))]
    [Migration("20210329175905_starupdate")]
    partial class starupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("albumtrackr.API.DTO.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AlbumListId")
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumListId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("albumtrackr.API.DTO.AlbumList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ALists");
                });

            modelBuilder.Entity("albumtrackr.API.DTO.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("albumListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("albumListId");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("albumtrackr.API.DTO.Album", b =>
                {
                    b.HasOne("albumtrackr.API.DTO.AlbumList", null)
                        .WithMany("Albums")
                        .HasForeignKey("AlbumListId");
                });

            modelBuilder.Entity("albumtrackr.API.DTO.Star", b =>
                {
                    b.HasOne("albumtrackr.API.DTO.AlbumList", null)
                        .WithMany("Stars")
                        .HasForeignKey("albumListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("albumtrackr.API.DTO.AlbumList", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
